runtime: nodejs16
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: artifacts/\1
    upload: artifacts/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: artifacts/index.html
    upload: artifacts/index.html