name: CI/CD


on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: 'false'
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: 16

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/416443939101/locations/global/workloadIdentityPools/bmwadforth-iam/providers/bmwadforth-iam-github'
          service_account: 'bmwadforth-dev-ci@digital-node-1176.iam.gserviceaccount.com'

      - id: 'npm-auth'
        name: 'Authenticate to GCP Artifact Registry'
        run: npx google-artifactregistry-auth

      - run: npm install
        name: Install

      - run: npm run build
        name: Build

      - run: npm run test
        name: Test

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    env:
      CI: 'false'
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: 16

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/416443939101/locations/global/workloadIdentityPools/bmwadforth-iam/providers/bmwadforth-iam-github'
          service_account: 'bmwadforth-dev-ci@digital-node-1176.iam.gserviceaccount.com'

      - id: 'npm-auth'
        name: 'Authenticate to GCP Artifact Registry'
        run: npx google-artifactregistry-auth

      - id: 'sdk'
        name: 'Setup Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - id: 'configure-docker'
        name: 'Configure docker'
        run: |
          gcloud auth configure-docker australia-southeast2-docker.pkg.dev

      - id: 'docker'
        name: 'Build and push image'
        uses: 'docker/build-push-action@v2'
        with:
          context: .
          push: true
          tags: australia-southeast2-docker.pkg.dev/digital-node-1176/bmwadforth-docker/bmwadforth-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ build, publish ]
    if: github.ref == 'refs/heads/master'

    env:
      CI: 'false'
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - uses: 'actions/checkout@v3'
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: 16

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/416443939101/locations/global/workloadIdentityPools/bmwadforth-iam/providers/bmwadforth-iam-github'
          service_account: 'bmwadforth-dev-ci@digital-node-1176.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          region: 'australia-southeast2'
          service: 'bmwadforth-frontend'
          image: 'australia-southeast2-docker.pkg.dev/digital-node-1176/bmwadforth-docker/bmwadforth-frontend:latest'